version: "3.8"

services:
    # React Vite app
    bazap-ui:
        build: ./bazap-ui
        ports:
            - "5173:5173"
        volumes:
            - ./bazap-ui:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: ["npm", "run", "dev"]

    # Node.js Express server
    server:
        build: ./server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/your_database_name

    # MongoDB service
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    # .NET Core project
    voucherexcel:
        build: ./VoucherExcel
        ports:
            - "5257:80"
        volumes:
            - ./VoucherExcel:/app
        depends_on:
            - server

volumes:
    mongo-data:
